### ISSUE TITLE
Crash bei falschem Hostnamen

### ISSUE THREAD

**Issue by Crazyachmed** [volkszaehler/app-android#22]
Unhandled Exception, wenn der Hostname nicht auflösbar ist

```
01-29 09:34:05.249 18405 18840 D Preferences: url: http://odroid.lan/vz/middleware.php/entity.json
01-29 09:34:05.249 18405 18840 D Preferences: urlDef: http://odroid.lan/vz/middleware.php/capabilities/definitions/entities.json
01-29 09:34:05.298 18405 18422 D mali_winsys: new_window_surface returns 0x3000
01-29 09:34:05.450 18405 18840 W System.err: java.net.UnknownHostException: Unable to resolve host "odroid.lan": No address associated with hostname
01-29 09:34:05.451 18405 18840 W System.err: 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:125)
01-29 09:34:05.451 18405 18840 W System.err: 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
01-29 09:34:05.451 18405 18840 W System.err: 	at java.net.InetAddress.getAllByName(InetAddress.java:752)
01-29 09:34:05.451 18405 18840 W System.err: 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:142)
01-29 09:34:05.451 18405 18840 W System.err: 	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
01-29 09:34:05.451 18405 18840 W System.err: 	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
01-29 09:34:05.451 18405 18840 W System.err: 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:366)
01-29 09:34:05.451 18405 18840 W System.err: 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
01-29 09:34:05.451 18405 18840 W System.err: 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
01-29 09:34:05.451 18405 18840 W System.err: 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
01-29 09:34:05.452 18405 18840 W System.err: 	at org.volkszaehler.volkszaehlerapp.ServiceHandler.makeServiceCall(ServiceHandler.java:145)
01-29 09:34:05.452 18405 18840 W System.err: 	at org.volkszaehler.volkszaehlerapp.ServiceHandler.makeServiceCall(ServiceHandler.java:108)
01-29 09:34:05.452 18405 18840 W System.err: 	at org.volkszaehler.volkszaehlerapp.ServiceHandler.makeServiceCall(ServiceHandler.java:65)
01-29 09:34:05.454 18405 18840 W System.err: 	at org.volkszaehler.volkszaehlerapp.Preferences$GetChannels.doInBackground(Preferences.java:189)
01-29 09:34:05.454 18405 18840 W System.err: 	at org.volkszaehler.volkszaehlerapp.Preferences$GetChannels.doInBackground(Preferences.java:143)
01-29 09:34:05.455 18405 18840 W System.err: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
01-29 09:34:05.455 18405 18840 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-29 09:34:05.455 18405 18840 W System.err: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
01-29 09:34:05.455 18405 18840 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-29 09:34:05.455 18405 18840 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-29 09:34:05.455 18405 18840 W System.err: 	at java.lang.Thread.run(Thread.java:761)
01-29 09:34:05.455 18405 18840 W System.err: Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
01-29 09:34:05.455 18405 18840 W System.err: 	at libcore.io.Posix.android_getaddrinfo(Native Method)
01-29 09:34:05.455 18405 18840 W System.err: 	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
01-29 09:34:05.455 18405 18840 W System.err: 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:106)
01-29 09:34:05.455 18405 18840 W System.err: 	... 20 more
01-29 09:34:05.471 18405 18840 W System.err: java.net.UnknownHostException: Unable to resolve host "odroid.lan": No address associated with hostname
01-29 09:34:05.472 18405 18840 W System.err: 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:95)
01-29 09:34:05.472 18405 18840 W System.err: 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
01-29 09:34:05.472 18405 18840 W System.err: 	at java.net.InetAddress.getAllByName(InetAddress.java:752)
01-29 09:34:05.472 18405 18840 W System.err: 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:142)
01-29 09:34:05.472 18405 18840 W System.err: 	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
01-29 09:34:05.472 18405 18840 W System.err: 	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
01-29 09:34:05.472 18405 18840 W System.err: 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:366)
01-29 09:34:05.472 18405 18840 W System.err: 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
01-29 09:34:05.472 18405 18840 W System.err: 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
01-29 09:34:05.472 18405 18840 W System.err: 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
01-29 09:34:05.472 18405 18840 W System.err: 	at org.volkszaehler.volkszaehlerapp.ServiceHandler.makeServiceCall(ServiceHandler.java:145)
01-29 09:34:05.472 18405 18840 W System.err: 	at org.volkszaehler.volkszaehlerapp.ServiceHandler.makeServiceCall(ServiceHandler.java:108)
01-29 09:34:05.472 18405 18840 W System.err: 	at org.volkszaehler.volkszaehlerapp.ServiceHandler.makeServiceCall(ServiceHandler.java:65)
01-29 09:34:05.472 18405 18840 W System.err: 	at org.volkszaehler.volkszaehlerapp.Preferences$GetChannels.doInBackground(Preferences.java:190)
01-29 09:34:05.472 18405 18840 W System.err: 	at org.volkszaehler.volkszaehlerapp.Preferences$GetChannels.doInBackground(Preferences.java:143)
01-29 09:34:05.472 18405 18840 W System.err: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
01-29 09:34:05.472 18405 18840 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-29 09:34:05.472 18405 18840 W System.err: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
01-29 09:34:05.472 18405 18840 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-29 09:34:05.473 18405 18840 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-29 09:34:05.473 18405 18840 W System.err: 	at java.lang.Thread.run(Thread.java:761)
01-29 09:34:05.489 18405 18840 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
01-29 09:34:05.489 18405 18840 E AndroidRuntime: Process: org.volkszaehler.volkszaehlerapp, PID: 18405
01-29 09:34:05.489 18405 18840 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
01-29 09:34:05.489 18405 18840 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:325)
01-29 09:34:05.489 18405 18840 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
01-29 09:34:05.489 18405 18840 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
01-29 09:34:05.489 18405 18840 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
01-29 09:34:05.489 18405 18840 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
01-29 09:34:05.489 18405 18840 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-29 09:34:05.489 18405 18840 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-29 09:34:05.489 18405 18840 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
01-29 09:34:05.489 18405 18840 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.toString()' on a null object reference
01-29 09:34:05.489 18405 18840 E AndroidRuntime: 	at org.volkszaehler.volkszaehlerapp.Preferences$GetChannels.doInBackground(Preferences.java:256)
01-29 09:34:05.489 18405 18840 E AndroidRuntime: 	at org.volkszaehler.volkszaehlerapp.Preferences$GetChannels.doInBackground(Preferences.java:143)
01-29 09:34:05.489 18405 18840 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
01-29 09:34:05.489 18405 18840 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-29 09:34:05.489 18405 18840 E AndroidRuntime: 	... 4 more
```

**Comment by SirkoVZ** [comment]
fixed in https://github.com/volkszaehler/app-android/releases/tag/0.9.1

**Comment by SirkoVZ** [comment]
tested, works
